// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHqHTCroqJPmmhKM03VMSIKUo6zsgGQiQ',
    appId: '1:176005049277:web:657aa40db018aaf33d80d4',
    messagingSenderId: '176005049277',
    projectId: 'quiz-app-54498',
    authDomain: 'quiz-app-54498.firebaseapp.com',
    storageBucket: 'quiz-app-54498.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXFoYUZrqxTuqh9us29WRd_gWMhaKkUF8',
    appId: '1:176005049277:android:e31c47cbf06d8bf43d80d4',
    messagingSenderId: '176005049277',
    projectId: 'quiz-app-54498',
    storageBucket: 'quiz-app-54498.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOs-wpBVEnccLPYm2bPaHSpJx8GJEDGtM',
    appId: '1:176005049277:ios:5c079f7021d1724f3d80d4',
    messagingSenderId: '176005049277',
    projectId: 'quiz-app-54498',
    storageBucket: 'quiz-app-54498.firebasestorage.app',
    iosBundleId: 'com.example.quizapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOs-wpBVEnccLPYm2bPaHSpJx8GJEDGtM',
    appId: '1:176005049277:ios:5c079f7021d1724f3d80d4',
    messagingSenderId: '176005049277',
    projectId: 'quiz-app-54498',
    storageBucket: 'quiz-app-54498.firebasestorage.app',
    iosBundleId: 'com.example.quizapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHqHTCroqJPmmhKM03VMSIKUo6zsgGQiQ',
    appId: '1:176005049277:web:c8c5e761d8116d8e3d80d4',
    messagingSenderId: '176005049277',
    projectId: 'quiz-app-54498',
    authDomain: 'quiz-app-54498.firebaseapp.com',
    storageBucket: 'quiz-app-54498.firebasestorage.app',
  );

}